version: 0.2

env:
  variables:
    VPCID: "vpc-389d155e"
    SUBNETID: "subnet-342b346f"

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Windows 10 image...          
      - aws cloudformation deploy --stack-name "Windows-10-Build" --template-file ./cfn_builder.yml --parameter-overrides VPC=$VPCID Subnet=$SUBNETID --region eu-west-1  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deleting the build stack
      - aws cloudformation delete-stack --stack-name "Windows-10-Build" --region eu-west-1

