---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template deploys an i3.metal in a subnet that must be able to reach Internet
  The i3.metal instance then install VirtualBox and leverage packer for OS build
  At the end of the build, the OVA is uploaded to S3

#Metadata:
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnet:
    Type: AWS::EC2::Subnet::Id
Resources:
  rInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00035f41c82244dab
      InstanceType: m5d.large
      IamInstanceProfile: ec2-poweruser
      SecurityGroupIds:
        - !Ref rBuilderSG
      SubnetId: !Ref Subnet
      UserData: 
        'Fn::Base64': !Sub |
          #!/bin/bash
          # VARIABLES
          PACKER_URL="https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip"
          GITHUB_REPO="https://github.com/j2clerck/amazon-metal-ami-builder.git"
          ISO_URL="s3://clerckj/packer-windows/iso/Win10_1803_English_x64.iso"
          PACKER_BUILD_FILE="windows_10.json"
          BUILD_NAME="Windows_10"
          BUILD_VERSION="20181212"
          EC2_AVAIL_ZONE=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone`
          EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed 's/[a-z]$//'`"
          SIGNAL_URL=${rWaitHandle}
          # SETUP ENVIRONMENT
          apt update
          apt -y install unzip awscli nvme-cli git virtualbox jq
          DEVICE=$(nvme list | grep Instance -m 1 | awk -F ' ' '{ print $1 }')
          parted --script $DEVICE mklabel gpt
          parted --script $DEVICE mkpart primary 0% 100%
          mkfs.ext4 ${!DEVICE}p1
          mkdir /opt/workdir/
          mount ${!DEVICE}p1 /opt/workdir
          
  rBuilderSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupName: BuilderSG
      GroupDescription: BuilderSG with no inbound traffic
      VpcId: !Ref VPC
  rWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
  rWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: rInstance
    Properties:
      Handle: !Ref rWaitHandle
      Timeout: "3600"


