# © 2018 Amazon Web Services, Inc. or its affiliates. All Rights Reserved. 
# This AWS Content is provided subject to the terms of the AWS Customer Agreement 
# available at http://aws.amazon.com/agreement or other written agreement between 
# Customer and Amazon Web Services, Inc.

- hosts: all
  vars:
    packer_url: 'https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip'
    virtualbox_version: 'VirtualBox-5.2'
    windows_10_iso_url: 's3://clerckj/packer-windows/iso/Win10_1803_English_x64.iso'
    github_repo_url: 'https://github.com/j2clerck/amazon-metal-ami-builder/archive/master.zip'
  gather_facts: no
  pre_tasks:
    - name: PRE | check python2 is installed or install it
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true
  tasks:
    - name: PRE | wait for instance to be ready for SSH
      wait_for_connection:
        timeout: 900
    - name: INSTALL | install packages required
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - unzip
        - nvme-cli
        - python-pip
        - git
        - virtualbox
        - awscli
      become: true
    - name: CONFIG | find available nvme disk
      shell:
        cmd: nvme list | grep Instance | awk -F ' ' '{print $1}'
      register: nvme_part
      become: true
    - name: CONFIG | Create a partition on NVME
      parted:
        device: "{{ nvme_part.stdout_lines[0] }}"
        number: 1
        state: present
      become: true
    - name: CONFIG | format filesystem
      filesystem:
        dev: "{{ nvme_part.stdout_lines[0] }}p1"
        force: yes
        fstype: ext4
      become: true
      ignore_errors: yes
    - name: CONFIG | create mountpoint
      file:
        path: /opt/workdir
        state: directory
        mode: 0755
        owner: ubuntu
        group: ubuntu
      become: true
    - name: CONFIG | mount filesystem
      mount:
        path: /opt/workdir/
        src: "{{ nvme_part.stdout_lines[0] }}p1"
        state: mounted
        fstype: ext4
      become: true
    - name: CONFIG | download packer
      unarchive:
        src: "{{ packer_url }}"
        dest: /usr/bin/
        remote_src: yes
      become: true
    - name: CONFIG | make packer executable in /usr/bin
      file:
        path: /usr/bin/packer
        mode: 0755
      become: true
    - name: CONFIG | unzip Github Repo
      unarchive:
        src: "{{ github_repo_url }}"
        dest: /opt/workdir/
        remote_src: yes
    - name: CONFIG | download Windows10 ISO from S3
      shell:
        cmd: aws s3 cp {{ windows_10_iso_url }} /opt/workdir/amazon-metal-ami-builder-master/packer/iso/
    - name: BUILD | build Windows 10
      shell:
        cmd: "packer build --only virtualbox-iso windows_10.json"
      args:
        chdir: "/opt/workdir/amazon-metal-ami-builder-master/packer"  

    - name: BUILD | copy ova to s3
      shell:
        cmd: aws s3 cp /opt/workdir/amazon-metal-ami-builder/packer/output-virtualbox-iso/*.ova s3://clerckj/packer-artefacts/
