# © 2018 Amazon Web Services, Inc. or its affiliates. All Rights Reserved. 
# This AWS Content is provided subject to the terms of the AWS Customer Agreement 
# available at http://aws.amazon.com/agreement or other written agreement between 
# Customer and Amazon Web Services, Inc.

- hosts: all
  vars:
    packer_url: 'https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip'
    virtualbox_version: 'VirtualBox-5.2'
    windows_10_iso_url: 's3://clerckj/packer-windows/iso/Win10_1803_English_x64.iso'
    github_repo_url: 'https://github.com/j2clerck/amazon-metal-ami-builder/archive/master.zip'
  gather_facts: no
  pre_tasks:
    - name: Install Python2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true
  tasks:
    - name: Wait for system to become reachable over SSH
      wait_for_connection:
        timeout: 900
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - unzip
        - nvme-cli
        - python-pip
        - git
        - virtualbox
        - awscli
      become: true
    - name: Find available nvme partition
      shell:
        cmd: nvme list | grep Instance | awk -F ' ' '{print $1}'
      register: nvme_part
      become: true
    - name: "debug nvme"
      debug:
        msg: "{{ nvme_part }}"
    - name: Create a partition on NVME
      parted:
        device: "{{ nvme_part.stdout_lines[0] }}"
        number: 1
        state: present
      become: true
    - name: format filesystem
      filesystem:
        dev: "{{ nvme_part.stdout_lines[0] }}p1"
        force: yes
        fstype: ext4
      become: true
      ignore_errors: yes
    - name: create folder
      file:
        path: /opt/workdir
        state: directory
        mode: 0755
        owner: ubuntu
        group: ubuntu
      become: true
    - name: mount filesystem
      mount:
        path: /opt/workdir/
        src: "{{ nvme_part.stdout_lines[0] }}p1"
        state: mounted
        fstype: ext4
      become: true
    - name: create folder
      file:
        path: /opt/workdir
        state: directory
        mode: 0755
        owner: ubuntu
        group: ubuntu
      become: true
    - name: Unzip packer
      unarchive:
        src: "{{ packer_url }}"
        dest: /opt/workdir/
        remote_src: yes
      become: true
    - name: Make packer executable
      file:
        path: /opt/workdir/packer
        mode: 0755
      become: true
    - name: Unzip Github Repo
      unarchive:
        src: "{{ github_repo_url }}"
        dest: /opt/workdir/
        remote_src: yes
      become: true
    - name: Copy Windows10 from S3
      shell:
        cmd: aws s3 cp {{ windows_10_iso_url }} /opt/workdir/amazon-metal-ami-builder-master/packer/iso/
    # - name: build Windows 10
    #   shell:
    #     cmd: "/opt/workdir/packer build --only virtualbox-iso windows_10.json"
    #   args:
    #     chdir: "/opt/workdir/amazon-metal-ami-builder/packer/"  

    # - name: copy ova to s3
    #   shell:
    #     cmd: aws s3 cp /opt/workdir/amazon-metal-ami-builder/packer/output-virtualbox-iso/*.ova s3://clerckj/packer-artefacts/
